### ISSUE TITLE
Add address batch mode

### ISSUE THREAD

**Issue by laurahaley** [City-of-Bloomington/master_address#1]
When using batch mode for more than 2 consecutive address additions,  if action is Add, it switches back to Assign as action after 2nd entry

**Comment by laurahaley** [comment]
batch mode is missing for multiple address entry on new interface

**Comment by inghamn** [comment]
Are there recommendations on what the CSV fields should be?  I'm open to whatever ordering; but more importantly, I'm wondering about all the lookup values.  In the case of subunits, there were only a small number of these fields (subuntType_id, locationType_id, and contact_id).  For subunits, I ended up telling people to use the names for subunitTypes and locationTypes, instead of the ID numbers. However, I thought it best to use the ID number for the contact person, to avoid confusion.

For addresses, there are several more foreign key fields to fill out. (addressType, jurisdiction, town, subdivision, plat, locationType, and contact person).  Some of these might best use the names for the values (instead of the ID number).  AddressType, jurisdiction, Township, and maybe even Subdivision could probably all be name values.  I'm a little worried about typos and confusion for the others.  Subdivision, Plat, and Contact person might best be done using the ID numbers.

Is it okay to require a mix of string values and ID numbers for these fields?

**Comment by laurahaley** [comment]
I think it's fine either way, an excel template would be helpful with
pull-downs would be helpful . I think I started one a while back.. I'll get
it to you.

Laura Haley
GIS Manager
City of Bloomington, IN
Information & Technology Services
812.349-3599
haleyl@bloomington.in.gov
http://bloomington.in.gov/gis

**Comment by laurahaley** [comment]
Here is the sample upload template. I can turn it into a google sheet if helpful.
[samplebulksubunitsheet.xlsx](https://github.com/City-of-Bloomington/master_address/files/5057880/samplebulksubunitsheet.xlsx)

**Comment by inghamn** [comment]
The subdivision and plats are way too many to do in a drop down.  Staff will need to browse Master Address to find the plat or subdivision, and type them carefully and accurately.

I think it might be better to use the subdivision and plat names in the spreadsheet, instead of the IDs, though.  That way, they can visually confirm it's the one they want.  A mistyped ID number would not be obvious to anyone.

However, with the number of address fields to fill out, the spreadsheet is going to be very wide.

**Comment by inghamn** [comment]
Well, alas.  It turns out, Plat and Subdivision names are not unique, so we cannot use them in the spreadsheet as identities.  The Plat and Subdivision columns must contain ID numbers, instead of names.

**Comment by laurahaley** [comment]
I think we can definitely skip subdivisions since we don't use that and
it's fine to use the plat id, and it is probably perferable since the plat
names can be tricky.

These are the fields I think we need for addresses

status
address_type
street number prefix
street number
street number suffix
street id
zip code
zip plus 4
jurisdiction
plat id
plat_lot_number
Township
Section
Quarter Section (optional)
Address Notes
location use type
mailable
occupiable
group quarters
contact id
change notes





Laura Haley
GIS Manager
City of Bloomington, IN
Information & Technology Services
812.349-3599
haleyl@bloomington.in.gov
http://bloomington.in.gov/gis
