### ISSUE TITLE
 Error when adding new street

### ISSUE THREAD

**Issue by laurahaley** [City-of-Bloomington/master_address#119]
I added two new street names, W Thornbury DR and N Westbury Village DR. I get a "Get Sorry there is already an active transaction" error when trying to create new streets with these names.

**Comment by inghamn** [comment]
The transaction I added to fix #118 is causing this error.  Street::Add calls Street::AddDesignation.  Since they both are database transactions, the effect is to attempt to nest the Designation transaction inside of the Add transaction, which is not possible.

I need to modify the database code so that the AddDesignation queries are seperate from the transaction controls.
