### ISSUE TITLE
Address change status

### ISSUE THREAD

**Issue by inghamn** [City-of-Bloomington/master_address#33]
Address retire and unretire should be the same action; "changeStatus".  This is similar to what we did for streets. 

There is currently no way to make an address go from "proposed" to "current".  We should create a "changeStatus" action that handles all statuses, instead of trying to create a seperate action for each state change between statuses.

**Comment by inghamn** [comment]
We'll need to do the same for Subunits. 

Changing an address status should change the status of all subunits for that address that had the previous status.  It should also change the status for the "active" location for that address.

For example, when changing an address from "current" to "retired", all subunits that are "current" should also be changed to "retired".  The active location for the address should also be set to "retired".

**Comment by laurahaley** [comment]
What will happen when the address is retired due to readdress action?  In
this case, the subunits may or may not need to be to be retired.  I can't
think which is more likely, it just depends.  Maybe the app could give an
option on what to do with the subunits, leave current or retire. If we
don't do that, then it is safer not to retire the subunits and have the
user retire the subunits explicitly.


Laura Haley
GIS Manager
City of Bloomington, IN
Information & Technology Services
812.349-3599
haleyl@bloomington.in.gov
http://bloomington.in.gov/gis

**Comment by inghamn** [comment]
It may be better to have employees retire the subunits seperately from the address, then.  That way it's up to the employee to know whether they *should* retire the subunits or not.

**Comment by inghamn** [comment]
This is not part of the readdress action.  That action will have it's own logic for what to do with subunits and locations.  This is only for manually changing the status on an address.
