### ISSUE TITLE
Activity reports not getting updated with recent changes

### ISSUE THREAD

**Issue by laurahaley** [City-of-Bloomington/master_address#92]
I've added new addresses and updated an existing address and they do not appear in the activity list on the home screen or the activity report. These addresses are in Ellettsville and the County
- 7236 W Mustang DR - new address - https://bloomington.in.gov/master_address/addresses/71029
- 2000 S State Road 446 - updated address - https://bloomington.in.gov/master_address/addresses/29140

**Comment by inghamn** [comment]
7236 W Mustang Dr is, in fact, showing up in the County-Wide report.  However, I just realized that the sorting for that report is showing oldest first.  I should change the report sorting so that the most recent changes are shown first.

2000 S State Road 446 is not showing up in the County-wide report at all.  I am still looking into it.

**Comment by inghamn** [comment]
2000 S State Road 446 is not included because my query is not retrieving street names without a suffix code.  I'll update the query to do a left join on street_types.
